<?php

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

return [
        [
            'nama_kelurahan' => 'Bambankerep',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374160',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
        [
            'nama_kelurahan' => 'Bandarharjo',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374120',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
        [
            'nama_kelurahan' => 'Bangetayu Kulon',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374090',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
        [
            'nama_kelurahan' => 'Bangetayu Wetan',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374090',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
        [
            'nama_kelurahan' => 'Bangunharjo',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374130',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
        [
            'nama_kelurahan' => 'Banjardowo',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374090',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
        [
            'nama_kelurahan' => 'Banyumanik',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374030',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
        [
            'nama_kelurahan' => 'Barusari',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374050',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Bendan Duwur',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374040',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,
        [
            'nama_kelurahan' => 'Bendan Ngisor',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374040',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,
        [
            'nama_kelurahan' => 'Bendungan',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374040',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,
        [
            'nama_kelurahan' => 'Bojongsalaman',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374140',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,
        [
            'nama_kelurahan' => 'Bongsari',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374140',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Bringin',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374160',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Brumbungan',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374130',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Bubakan',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374010',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Bugangan',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374110',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Bulu Lor',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374120',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Bulusan',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374070',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Bulustalan',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374050',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Cabean',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374140',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Candi',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374060',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Cangkiran',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374010',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Cepoko',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374020',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Dadapsari',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374120',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Gabahan',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374130',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Gajahmungkur',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374040',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Gayamsari',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374100',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Gebangsari',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374090',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Gedawang',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374030',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Gemah',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374080',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Genuksari',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374090',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Gisikdrono',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374140',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Gondoriyo',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374160',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Gunungpati',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374020',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Jabungan',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374030',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Jagalan',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374130',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Jangli',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374070',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Jatibarang',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374010',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Jatingaleh',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374060',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Jatirejo',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374020',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Jatisari',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374010',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Jerakah',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374150',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Jomblang',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374060',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Kalibanteng Kidul',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374140',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Kalibanteng Kulon',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374140',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Kalicari',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374080',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Kaligawe',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374100',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Kalipancur',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374160',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Kalisegoro',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374020',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Kaliwiru',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374060',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Kandri',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374020',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Karang Ayu',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374140',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Karang Rejo',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374040',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Karanganyar',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374150',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Karanganyar Gunung',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374060',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Karangkidul',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374130',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Karangmalang',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374010',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Karangroto',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374090',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Karangtempel',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374110',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Karangturi',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374110',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Kauman',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374130',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Kebonagung',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374110',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Kedungmundu',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374070',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Kedungpani',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374010',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Kembangarum',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374140',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Kembangsari',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374130',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Kemijen',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374110',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Kramas',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374070',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Kranggan',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374130',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Krapyak',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374140',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Krobokan',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374140',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Kudu',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374090',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Kuningan',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374120',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Lamper Kidul',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374050',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Lamper Lor',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374050',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Lamper Tengah',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374050',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Lempongsari',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374040',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Mangkang Kulon',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374150',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Mangkang Wetan',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374150',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Mangunharjo',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374070',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Mangunharjo',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374150',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Mangunsari',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374020',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Manyaran',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374140',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Meteseh',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374070',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Mijen',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374010',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Miroto',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374130',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Mlatibaru',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374110',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Mlatiharjo',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374110',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Mugassari',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374050',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Muktiharjo Kidul',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374080',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Muktiharjo Lor',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374090',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Ngadirgo',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374010',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Ngaliyan',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374160',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Ngemplaksimongan',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374140',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Ngesrep',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374030',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Ngijo',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374020',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Nongkosawit',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374020',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Padangsari',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374030',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Pakintelan',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374020',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Palebon',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374080',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Pandansari',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374130',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Pandean Lamper',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374100',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Panggung Kidul',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374120',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Panggung Lor',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374120',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Patemon',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374020',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Pedalangan',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374030',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Pedurungan Kidul',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374080',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Pedurungan Lor',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374080',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Pedurungan Tengah',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374080',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Pekunden',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374130',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Pendrikan Kidul',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374130',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Pendrikan Lor',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374130',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Penggaron Kidul',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374080',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Penggaron Lor',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374090',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Pesantren',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374010',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Peterongan',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374050',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Petompon',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374040',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Plalangan',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374020',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Plamongan Sari',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374080',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Pleburan',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374050',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Plombokan',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374120',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Podorejo',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374160',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Polaman',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374010',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Pudakpayung',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374030',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Pungangan',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374020',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Purwodinatan',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374130',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Purwosari',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374010',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Purwosari',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374120',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Purwoyoso',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374160',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Randu Garut',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374150',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Randusari',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374050',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Rejomulyo',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374110',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Rejosari',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374110',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Rowosari',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374070',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Sadeng',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374020',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Salamanmloyo',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374140',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Sambirejo',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374100',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Sambiroto',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374070',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Sampangan',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374040',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Sarirejo',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374110',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Sawahbesar',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374100',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Sekaran',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374020',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Sekayu',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374130',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Sembungharjo',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374090',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Sendangguwo',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374070',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Sendangmulyo',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374070',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Siwalan',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374100',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Srondol Kulon',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374030',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Srondol Wetan',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374030',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Sukorejo',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374020',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Sumurboto',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374030',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Sumurejo',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374020',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Tambak Harjo',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374140',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Tambakaji',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374160',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Tambakrejo',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374100',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Tambangan',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374010',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Tandang',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374070',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Tanjungmas',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374120',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Tawangmas',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374140',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Tawangsari',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374140',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
        [
            'nama_kelurahan' => 'Tegalsari',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374060',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
        [
            'nama_kelurahan' => 'Tembalang',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374070',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
        [
            'nama_kelurahan' => 'Terboyo Kulon',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374090',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
        [
            'nama_kelurahan' => 'Terboyo Wetan',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374090',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
        [
            'nama_kelurahan' => 'Tinjomoyo',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374030',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
        [
            'nama_kelurahan' => 'Tlogomulyo',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374080',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
        [
            'nama_kelurahan' => 'Tlogosari Kulon',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374080',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
        [
            'nama_kelurahan' => 'Tlogosari Wetan',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374080',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
        [
            'nama_kelurahan' => 'Trimulyo',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374090',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
        [
            'nama_kelurahan' => 'Tugurejo',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374150',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
        [
            'nama_kelurahan' => 'Wates',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374160',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
        [
            'nama_kelurahan' => 'Wonodri',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374050',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
        [
            'nama_kelurahan' => 'Wonolopo',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374010',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Wonoplumbon',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374010',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Wonosari',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374160',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    ,

        [
            'nama_kelurahan' => 'Wonotingal',
            'provinsi_id' => 1,
            'kabupaten_id' => 1,
            'kecamatan_id' => 'id3374060',
            'created_at' => Carbon::now('Asia/Jakarta'),
            'updated_at' => Carbon::now('Asia/Jakarta'),
        ],
    
];